/**
 * Generator Tests
 * doc-gen - Skylily 🌸
 */

import { describe, it, expect } from 'vitest';
import { generateDocumentation, GeneratorOptions } from '../src/generator.js';
import { ParsedFile, DocFunction, DocClass, DocInterface, DocType } from '../src/parser.js';

describe('Generator', () => {
  describe('generateDocumentation', () => {
    it('should generate documentation with title', () => {
      const files: ParsedFile[] = [];
      const options: GeneratorOptions = { title: 'My API Docs' };
      
      const result = generateDocumentation(files, options);
      
      expect(result).toContain('# My API Docs');
    });
    
    it('should include generation date', () => {
      const files: ParsedFile[] = [];
      const result = generateDocumentation(files);
      
      expect(result).toMatch(/Generated by doc-gen on \d{4}-\d{2}-\d{2}/);
    });
    
    it('should generate function documentation', () => {
      const func: DocFunction = {
        name: 'calculateSum',
        description: 'Calculates the sum of an array of numbers',
        params: [
          { name: 'numbers', type: 'number[]', description: 'Array of numbers to sum' },
        ],
        returns: { type: 'number', description: 'The sum of all numbers' },
        async: false,
        exported: true,
        line: 10,
      };
      
      const files: ParsedFile[] = [{
        path: '/test/math.ts',
        functions: [func],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('## Functions');
      expect(result).toContain('`calculateSum`');
      expect(result).toContain('Calculates the sum of an array of numbers');
      expect(result).toContain('`numbers`');
      expect(result).toContain('`number[]`');
      expect(result).toContain('**Returns:**');
    });
    
    it('should generate async function signature', () => {
      const func: DocFunction = {
        name: 'fetchData',
        description: 'Fetches data asynchronously',
        params: [{ name: 'url', type: 'string', description: '' }],
        returns: { type: 'Promise<Response>', description: '' },
        async: true,
        exported: true,
        line: 1,
      };
      
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [func],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('async fetchData');
    });
    
    it('should generate class documentation', () => {
      const cls: DocClass = {
        name: 'UserService',
        description: 'Service for managing users',
        methods: [
          {
            name: 'getUser',
            description: 'Gets a user by ID',
            params: [{ name: 'id', type: 'string', description: 'User ID' }],
            returns: { type: 'User', description: '' },
            async: false,
            exported: true,
            line: 5,
          },
        ],
        properties: [
          {
            name: 'baseUrl',
            type: 'string',
            description: 'Base URL for API',
            visibility: 'public',
          },
        ],
        implements: [],
        exported: true,
        line: 1,
      };
      
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [],
        classes: [cls],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('## Classes');
      expect(result).toContain('### `UserService`');
      expect(result).toContain('Service for managing users');
      expect(result).toContain('#### Properties');
      expect(result).toContain('`baseUrl`');
      expect(result).toContain('#### Methods');
      expect(result).toContain('`getUser`');
    });
    
    it('should generate class with extends and implements', () => {
      const cls: DocClass = {
        name: 'AdminUser',
        description: 'An admin user',
        extends: 'BaseUser',
        implements: ['Serializable', 'Comparable'],
        methods: [],
        properties: [],
        exported: true,
        line: 1,
      };
      
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [],
        classes: [cls],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('**Extends:** `BaseUser`');
      expect(result).toContain('**Implements:** `Serializable`, `Comparable`');
    });
    
    it('should generate interface documentation', () => {
      const iface: DocInterface = {
        name: 'Config',
        description: 'Application configuration',
        properties: [
          { name: 'apiKey', type: 'string', optional: false, description: 'API key' },
          { name: 'timeout', type: 'number', optional: true, description: 'Timeout in ms' },
        ],
        exported: true,
        line: 1,
      };
      
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [],
        classes: [],
        interfaces: [iface],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('## Interfaces');
      expect(result).toContain('### `Config`');
      expect(result).toContain('Application configuration');
      expect(result).toContain('| `apiKey`');
      expect(result).toContain('| `timeout`');
      expect(result).toMatch(/timeout.*✓/); // optional marker
    });
    
    it('should generate type alias documentation', () => {
      const type: DocType = {
        name: 'Status',
        description: 'Possible status values',
        definition: "'pending' | 'active' | 'completed'",
        exported: true,
        line: 1,
      };
      
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [],
        classes: [],
        interfaces: [],
        types: [type],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('## Types');
      expect(result).toContain('### `Status`');
      expect(result).toContain('Possible status values');
      expect(result).toContain("type Status = 'pending' | 'active' | 'completed'");
    });
    
    it('should include table of contents by default', () => {
      const func: DocFunction = {
        name: 'testFunc',
        description: 'A test function',
        params: [],
        returns: { type: 'void', description: '' },
        async: false,
        exported: true,
        line: 1,
      };
      
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [func],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('## Table of Contents');
      expect(result).toContain('### Functions');
      expect(result).toContain('- [`testFunc`]');
    });
    
    it('should disable table of contents when option is false', () => {
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [{
          name: 'test',
          description: '',
          params: [],
          returns: { type: 'void', description: '' },
          async: false,
          exported: true,
          line: 1,
        }],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files, { includeTableOfContents: false });
      
      expect(result).not.toContain('## Table of Contents');
    });
    
    it('should include private members when option is true', () => {
      const cls: DocClass = {
        name: 'Test',
        description: '',
        methods: [],
        properties: [
          { name: 'publicProp', type: 'string', description: '', visibility: 'public' },
          { name: 'privateProp', type: 'string', description: '', visibility: 'private' },
        ],
        implements: [],
        exported: true,
        line: 1,
      };
      
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [],
        classes: [cls],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const withPrivate = generateDocumentation(files, { includePrivate: true });
      const withoutPrivate = generateDocumentation(files, { includePrivate: false });
      
      expect(withPrivate).toContain('privateProp');
      expect(withoutPrivate).not.toContain('privateProp');
    });
    
    it('should group by file when option is true', () => {
      const files: ParsedFile[] = [
        {
          path: '/src/utils.ts',
          functions: [{
            name: 'utilFunc',
            description: '',
            params: [],
            returns: { type: 'void', description: '' },
            async: false,
            exported: true,
            line: 1,
          }],
          classes: [],
          interfaces: [],
          types: [],
          exports: [],
        },
        {
          path: '/src/helpers.ts',
          functions: [{
            name: 'helperFunc',
            description: '',
            params: [],
            returns: { type: 'void', description: '' },
            async: false,
            exported: true,
            line: 1,
          }],
          classes: [],
          interfaces: [],
          types: [],
          exports: [],
        },
      ];
      
      const result = generateDocumentation(files, { groupByFile: true });
      
      expect(result).toContain('## utils.ts');
      expect(result).toContain('## helpers.ts');
    });
    
    it('should sort items alphabetically by default', () => {
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [
          { name: 'zebra', description: '', params: [], returns: { type: 'void', description: '' }, async: false, exported: true, line: 1 },
          { name: 'apple', description: '', params: [], returns: { type: 'void', description: '' }, async: false, exported: true, line: 2 },
          { name: 'mango', description: '', params: [], returns: { type: 'void', description: '' }, async: false, exported: true, line: 3 },
        ],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      const appleIndex = result.indexOf('`apple`');
      const mangoIndex = result.indexOf('`mango`');
      const zebraIndex = result.indexOf('`zebra`');
      
      expect(appleIndex).toBeLessThan(mangoIndex);
      expect(mangoIndex).toBeLessThan(zebraIndex);
    });
    
    it('should not include void return type description', () => {
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [{
          name: 'doSomething',
          description: 'Does something',
          params: [],
          returns: { type: 'void', description: '' },
          async: false,
          exported: true,
          line: 1,
        }],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      // Should not have "Returns: void" line
      expect(result).not.toMatch(/\*\*Returns:\*\*.*void/);
    });
    
    it('should handle empty files array', () => {
      const result = generateDocumentation([]);
      
      expect(result).toContain('# API Documentation');
      expect(result).not.toContain('## Functions');
      expect(result).not.toContain('## Classes');
    });
    
    it('should skip files with no documented items', () => {
      const files: ParsedFile[] = [{
        path: '/empty.ts',
        functions: [],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files, { groupByFile: true });
      
      expect(result).not.toContain('## empty.ts');
    });
    
    it('should filter out non-exported items by default', () => {
      const files: ParsedFile[] = [{
        path: '/test.ts',
        functions: [
          { name: 'exportedFunc', description: '', params: [], returns: { type: 'void', description: '' }, async: false, exported: true, line: 1 },
          { name: 'internalFunc', description: '', params: [], returns: { type: 'void', description: '' }, async: false, exported: false, line: 2 },
        ],
        classes: [],
        interfaces: [],
        types: [],
        exports: [],
      }];
      
      const result = generateDocumentation(files);
      
      expect(result).toContain('exportedFunc');
      expect(result).not.toContain('internalFunc');
    });
  });
});
